name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-jaclear        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and test order-service
        run: |
          cd order-service
          chmod +x mvnw
          ./mvnw clean test
